# Generated by Django 4.2 on 2023-04-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_remove_rubric_parent_delete_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='views',
        ),
    ]
